version: e.2

phases:
  install:
     commands:
       - "apt install unzip -y"
       - "wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip"
       - "unzip terraform_1.0.5_linux_amd64.zip"
       - "mv terraform /usr/local/bin/"
     pre-build:
       commands:
         - terraform init
     
     build:
       commands:
         -terraform $TF_COMMNAD -auto-approve
     
     post_build:
       commands:
         - echo terraform $TF_COMMAND completed on ´date´
         
